// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8seG2yl81uhycwyXzzRrX4NKGfsyXZ4',
    appId: '1:950492184348:web:26c3362000c489cf17c4d9',
    messagingSenderId: '950492184348',
    projectId: 'nmaxapp',
    authDomain: 'nmaxapp.firebaseapp.com',
    storageBucket: 'nmaxapp.firebasestorage.app',
    measurementId: 'G-66ZK2HLRJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtznEkVEG7sk5qAexwNPE0-FWwHUWPj-k',
    appId: '1:950492184348:android:78616f24016d9cf517c4d9',
    messagingSenderId: '950492184348',
    projectId: 'nmaxapp',
    storageBucket: 'nmaxapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiRUje_MNZ9mFwUJSPRL4LSlgBz5PkqA',
    appId: '1:950492184348:ios:eed7f0a64caef58717c4d9',
    messagingSenderId: '950492184348',
    projectId: 'nmaxapp',
    storageBucket: 'nmaxapp.firebasestorage.app',
    iosBundleId: 'com.example.nmax',
  );
}
